name: autosign

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 8 点运行
  push:
    branches:
      - main  # 仅对主分支进行触发，您可以根据需要更改分支名称
  workflow_dispatch:

jobs:
  run_daily_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        env:
          SCHOOL_ID: ${{绵阳城市学院}}
          ACCOUNT: ${{ 2022600237}}
          PASSWORD: ${{ Yjf3212560. }}
          LONGITUDE: ${{ 104.732689 }}
          LATITUDE: ${{ 29.313337 }}
          ADDRESS_NAME: ${{顺水农业投资开发有限公司}}
          ADDRESS: ${{ 四川省自贡市自流井区 }}
          PROVINCE: ${{ 四川省 }}
          CITY: ${{ 自贡市 }}
          PUSHPLUS_SET: ${{ 2 }}
          PUSHPLUS_TOKEN: ${{ 2 }}
        run: python main.py
